# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thiagovsk Personal Blog
email: thiago@pencillabs.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about software engineering, posts in english and 
  portugueese
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thiagovsk.github.io/" # the base hostname & protocol for your site
twitter_username: thiagovsk_
github_username:  thiagovsk

# Build settings
markdown: kramdown
