# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "@thiagovsk"
description: > # this means to ignore newlines until "email:"
   Meu dia dia como engenheiro de software

email: thiagitosouza@gmail.com 
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/mr-robot-screen.jpg"

name: 'Thiago Ribeiro'
author: '@thiagovsk'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://thiagovsk.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@thiagovsk'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/thiagovsk_
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/thiagovsk
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/thiagovsk
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

